### ISSUE TITLE
Client secret information should not be saved in tracked source code

### ISSUE THREAD

**Issue by rloutlaw** [Azure-Samples/active-directory-python-webapp-graphapi#9]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

The client secret (CLIENT_SECRET) information managed in config.py is handled in an insecure manner. It's way too easy to leak credentials through version control, and should be externalized into an environment variable. At the very least, config.py should be put in the default .gitignore to prevent accidental pushes w/ keys to cloned forks.

### Minimal steps to reproduce
> Follow the documentation and configure the config.py with the values in your application registration.

### Any log messages given by the failure
> None.

### Expected/desired behavior
> Secret information should be managed and consumed via environment variable or through a secrety store like Azure Key Vault.

### OS and Version?
> ALL

### Versions
>n/a

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rayluo** [comment]
A summary of an offline mail thread: we can probably still read eveything from a json file because JSON specs guarantees "what you save is what you get", without needing to deal with escaping special characters. We can provide a sample json snippet in the comments at the beginning of a sample source code, but we would NOT actually commit such json file into the repo. That is actually the [current approach used by ADAL Python](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/1.2.0/sample/client_credentials_sample.py#L21-L30).

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Python library. Check it out: https://github.com/Azure-Samples/ms-identity-python-webapp

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
